

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 your_project_name.asgi:application
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

  celery:
    build: .
    command: celery -A your_project_name worker -l info
    depends_on:
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A your_project_name beat -l info
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
